import tweepy

CONSUMER_KEY = '90ZmHgVKBE6XLM0ZgQAJHziB1'
CONSUMER_SECRET = 'motnoRyWli4BaJYXiQfXo9JSQL8d1Px5umX76iaUe6uqxhG839'
ACCESS_TOKEN = '238842641-XjZ9MPWaiYhxY3bC1TlRCLGOYeBkAe7iyCmoai55'
ACCESS_TOKEN_SECRET = 'qrOTgcSKWExS5W32u4kZieunNJYiQfQUcbP3co9vuPkBD'

auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
auth.set_access_token(ACCESS_TOKEN, ACCESS_TOKEN_SECRET)
twitter_api = tweepy.API(auth)